#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import re
import argparse

foreground_color = 97
base_colors = {
    'A': 44,
    'C': 41,
    'G': 42,
    'T': 43,
    'U': 45,
    'N': 100,
}

#find the spans of specific tab-separated columns in a given line
def find_column_spans(line, columns):
    matches = []

    previous_pos = -1
    column_number = 0
    while True:
        pos = line.find('\t', previous_pos + 1)
        if pos == -1:
            break

        column_number += 1
        if column_number in columns:
            matches.append( (previous_pos + 1, pos) )

        previous_pos = pos

    #last (or only) column in the row
    column_number += 1
    if column_number in columns:
        matches.append( (previous_pos + 1, len(line)) )

    return matches

def main(argv=None):
    if argv is None:
        argv = sys.argv

    #prepare description and epilog texts (shown for --help) 
    help_description = 'This script reads lines from STDIN or a file, identifies strings of DNA/RNA and writes colored output to STDOUT.'
    help_description += ' When a file name is provided, files ending in .gz will be decompressed on the fly and the file format will be detected based on the extension.'

    help_epilog = ''    
    help_epilog += 'examples:\n  head reads.fastq | {}\n  {} genome.fa\n\n'.format(sys.argv[0], sys.argv[0])
    help_epilog += 'color scheme: '
    for base in ['A', 'T', 'C', 'G', 'U', 'N']:
        help_epilog += ' \033[{}m\033[{}m {} \033[0m'.format(foreground_color, base_colors[base], base)

    #parse command-line arguments
    parser = argparse.ArgumentParser(description = help_description,
        epilog = help_epilog,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-w", "--wide",
        help="wide output, add spaces around each base",
        action='store_true')
    parser.add_argument("-f", "--format",
        help="file format (auto|text|sam|vcf|fastq|fasta)",
        default='auto')
    parser.add_argument("file", nargs="?",
        help="file name to read (default: read from STDIN)",
        default='-')
    args = parser.parse_args(argv[1:])

    #open the file if we're not reading from stdin
    if args.file and args.file != '-':
        if args.file.endswith('.gz'):
            import gzip
            file_in = gzip.open(args.file, 'rb')
            filename = args.file[:-3]
        else:
            file_in = open(args.file, 'r')
            filename = args.file

        if args.format == 'auto':
            if filename.endswith('.sam'):
                args.format = 'sam'
            elif filename.endswith('.vcf'):
                args.format = 'vcf'
            elif filename.endswith('.fasta') or filename.endswith('.fa'):
                args.format = 'fasta'
            elif filename.endswith('.fastq') or filename.endswith('.fq'):
                args.format = 'fastq'
    else:
        file_in = sys.stdin

    #read input line by line (note: this will not work well when streaming long lines)
    try:
        line_counter = 0

        for line in file_in:
            last_match_end = 0

            #only parse specific lines
            do_search = True
            if args.format == 'fastq':
                #only color the second line per read (sequence)
                line_counter += 1
                do_search = line_counter % 4 == 2
            elif args.format == 'fasta':
                #do not color id rows
                do_search = not line.startswith('>')
            elif args.format == 'vcf':
                #ignore comments
                do_search = not line.startswith('#')
            elif args.format == 'sam':
                #ignore header
                do_search = not line.startswith('@')

            if not do_search:
                sys.stdout.write(line)
            else:
                if args.format == 'sam':
                    #only color column #10 (SEQ)
                    matches = find_column_spans(line, [10])
                elif args.format == 'vcf':
                    #only color columns #4+5 (REF+ALT)
                    matches = find_column_spans(line, [4, 5])
                elif args.format == 'fastq' or args.format == 'fasta':
                    #color the entire line, except the \n at the end
                    matches = [ (0, len(line)-1) ]
                else:
                    #search for strings of DNA/RNA in text
                    pattern = '\\b[ACGTUN]+\\b'
                    matches = [match.span(0) for match in re.finditer(pattern, line)]

                for match_start, match_end in matches:
                    #write characters before this string
                    if match_start > 0:
                        sys.stdout.write(line[last_match_end:match_start])

                    #loop through bases
                    previous_base = ''                
                    for i in range(match_start, match_end):
                        base = line[i]
                        
                        if base in base_colors:
                            #set color, but only if we have to
                            if previous_base == '':
                                #make sure we have the correct foreground color
                                sys.stdout.write('\033[{}m'.format(foreground_color))

                            if base != previous_base:
                                sys.stdout.write('\033[{}m'.format(base_colors[base]))
                                previous_base = base
                        else:
                            #unknown base, reset to default
                            if previous_base != '':
                                sys.stdout.write('\033[0m')
                                previous_base = ''

                        #write base out
                        if args.wide:
                            sys.stdout.write(' {} '.format(base))
                        else:
                            sys.stdout.write(base)

                    #remember how far we have written already
                    last_match_end = match_end

                    #make sure we have default options again
                    sys.stdout.write('\033[0m')

                #write the rest of the line
                sys.stdout.write(line[last_match_end:])

        #flush output
        sys.stdout.flush()
    except:
        #try to reset color settings, even if we are interrupted
        try:
            sys.stdout.write('\033[0m')
            sys.stdout.flush()
        except:
            pass

        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main())